# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-01 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170501_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pingyin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
