# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-01 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_pingyin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='pingyin',
            new_name='pinyin',
        ),
    ]
