# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-01 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170501_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pinyin',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
